
# Version 2 - For SOLR and Muscat 3

config:
    :version: 2.0
    :model: institution

fields:  
    "001":
    "008":
    "024a":
    "043c":
    "110a":
    "110c":
    "110g":
    "110g_facet":
      :type: text
      :from_tag: "110"
      :from_subtag: "g"
      :as: "110g_facet_sm"
    "410a":
    "371a":
    "371u":
    "580x":
    "5800":
    "680i":
